language: node_js
dist: trusty

addons:
  chrome: stable

git:
  depth: 10

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

cache:
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/v3/library-before-install.sh)

install:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/v3/library-install.sh)

script:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/v3/library-script.sh)

after_script:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/v3/library-after-script.sh)

after_success:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/v3/library-after-success.sh)

after_failure:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/v3/library-after-failure.sh)
